# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_if_pb2 as my__if__pb2


class GrpcViewerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/my_if.GrpcViewer/SayHello',
                request_serializer=my__if__pb2.GrpcViewerHelloRequest.SerializeToString,
                response_deserializer=my__if__pb2.GrpcViewerHelloReply.FromString,
                )
        self.DoAction = channel.unary_unary(
                '/my_if.GrpcViewer/DoAction',
                request_serializer=my__if__pb2.GrpcViewerActionRequest.SerializeToString,
                response_deserializer=my__if__pb2.GrpcViewerActionResponse.FromString,
                )


class GrpcViewerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcViewerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=my__if__pb2.GrpcViewerHelloRequest.FromString,
                    response_serializer=my__if__pb2.GrpcViewerHelloReply.SerializeToString,
            ),
            'DoAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DoAction,
                    request_deserializer=my__if__pb2.GrpcViewerActionRequest.FromString,
                    response_serializer=my__if__pb2.GrpcViewerActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'my_if.GrpcViewer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcViewer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/my_if.GrpcViewer/SayHello',
            my__if__pb2.GrpcViewerHelloRequest.SerializeToString,
            my__if__pb2.GrpcViewerHelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/my_if.GrpcViewer/DoAction',
            my__if__pb2.GrpcViewerActionRequest.SerializeToString,
            my__if__pb2.GrpcViewerActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
