# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_if.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my_if.proto',
  package='my_if',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmy_if.proto\x12\x05my_if\"&\n\x16GrpcViewerHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x14GrpcViewerHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"d\n\x17GrpcViewerActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"e\n\x18GrpcViewerActionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x32\xa5\x01\n\nGrpcViewer\x12H\n\x08SayHello\x12\x1d.my_if.GrpcViewerHelloRequest\x1a\x1b.my_if.GrpcViewerHelloReply\"\x00\x12M\n\x08\x44oAction\x12\x1e.my_if.GrpcViewerActionRequest\x1a\x1f.my_if.GrpcViewerActionResponse\"\x00\x62\x06proto3'
)




_GRPCVIEWERHELLOREQUEST = _descriptor.Descriptor(
  name='GrpcViewerHelloRequest',
  full_name='my_if.GrpcViewerHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='my_if.GrpcViewerHelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)


_GRPCVIEWERHELLOREPLY = _descriptor.Descriptor(
  name='GrpcViewerHelloReply',
  full_name='my_if.GrpcViewerHelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='my_if.GrpcViewerHelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=101,
)


_GRPCVIEWERACTIONREQUEST = _descriptor.Descriptor(
  name='GrpcViewerActionRequest',
  full_name='my_if.GrpcViewerActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='my_if.GrpcViewerActionRequest.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='my_if.GrpcViewerActionRequest.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='my_if.GrpcViewerActionRequest.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='my_if.GrpcViewerActionRequest.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='my_if.GrpcViewerActionRequest.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=203,
)


_GRPCVIEWERACTIONRESPONSE = _descriptor.Descriptor(
  name='GrpcViewerActionResponse',
  full_name='my_if.GrpcViewerActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='my_if.GrpcViewerActionResponse.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='my_if.GrpcViewerActionResponse.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='my_if.GrpcViewerActionResponse.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='my_if.GrpcViewerActionResponse.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='my_if.GrpcViewerActionResponse.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=306,
)

DESCRIPTOR.message_types_by_name['GrpcViewerHelloRequest'] = _GRPCVIEWERHELLOREQUEST
DESCRIPTOR.message_types_by_name['GrpcViewerHelloReply'] = _GRPCVIEWERHELLOREPLY
DESCRIPTOR.message_types_by_name['GrpcViewerActionRequest'] = _GRPCVIEWERACTIONREQUEST
DESCRIPTOR.message_types_by_name['GrpcViewerActionResponse'] = _GRPCVIEWERACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcViewerHelloRequest = _reflection.GeneratedProtocolMessageType('GrpcViewerHelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRPCVIEWERHELLOREQUEST,
  '__module__' : 'my_if_pb2'
  # @@protoc_insertion_point(class_scope:my_if.GrpcViewerHelloRequest)
  })
_sym_db.RegisterMessage(GrpcViewerHelloRequest)

GrpcViewerHelloReply = _reflection.GeneratedProtocolMessageType('GrpcViewerHelloReply', (_message.Message,), {
  'DESCRIPTOR' : _GRPCVIEWERHELLOREPLY,
  '__module__' : 'my_if_pb2'
  # @@protoc_insertion_point(class_scope:my_if.GrpcViewerHelloReply)
  })
_sym_db.RegisterMessage(GrpcViewerHelloReply)

GrpcViewerActionRequest = _reflection.GeneratedProtocolMessageType('GrpcViewerActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRPCVIEWERACTIONREQUEST,
  '__module__' : 'my_if_pb2'
  # @@protoc_insertion_point(class_scope:my_if.GrpcViewerActionRequest)
  })
_sym_db.RegisterMessage(GrpcViewerActionRequest)

GrpcViewerActionResponse = _reflection.GeneratedProtocolMessageType('GrpcViewerActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRPCVIEWERACTIONRESPONSE,
  '__module__' : 'my_if_pb2'
  # @@protoc_insertion_point(class_scope:my_if.GrpcViewerActionResponse)
  })
_sym_db.RegisterMessage(GrpcViewerActionResponse)



_GRPCVIEWER = _descriptor.ServiceDescriptor(
  name='GrpcViewer',
  full_name='my_if.GrpcViewer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=309,
  serialized_end=474,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='my_if.GrpcViewer.SayHello',
    index=0,
    containing_service=None,
    input_type=_GRPCVIEWERHELLOREQUEST,
    output_type=_GRPCVIEWERHELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoAction',
    full_name='my_if.GrpcViewer.DoAction',
    index=1,
    containing_service=None,
    input_type=_GRPCVIEWERACTIONREQUEST,
    output_type=_GRPCVIEWERACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCVIEWER)

DESCRIPTOR.services_by_name['GrpcViewer'] = _GRPCVIEWER

# @@protoc_insertion_point(module_scope)
